### ISSUE TITLE
Add non-priveleged user

### ISSUE THREAD

**Issue by ManoMarks** [play-with-docker/play-with-docker#106]
Add in a nonprivileged user to base image so we can more easily run labs like this:
https://github.com/docker/labs/tree/master/security/userns

**Comment by marcosnils** [comment]
Hey mano, adding an additional user won't help because the docker daemon is configured to be executed `only` by root in PWD. 

The tutorial can still be done and it'll work. You can stop/start the daemon with  userns support and check that that the user in the container is not the same as the one in the underlying system. In addition to that, the tutorial executes the `docker` by using `sudo`, so it's seems irrelevant to add a non-privileged user if you're still using `sudo` anyways. 

I think this can be closed and the tutorial can be easily ported to the training site. WDYT?
