### ISSUE TITLE
Add tutorials

### ISSUE THREAD

**Issue by marcosnils** [play-with-docker/play-with-docker#12]
It'd be amazing to have something like golang (https://tour.golang.org/welcome/1) using play-with-docker.

We definitely need to structure in a way that's easy for collaborators to add new sections and content.

**Comment by stealthybox** [comment]
just brainstorming:
- markdown for the content sections
- we need some way to effectively show users when to switch to certain docker instances
(since we're not working with a single console like Go)
- where does the tutorial button go?
- we could anchor the instance buttons in the tutorial content by index
- sidebar on the left of the instance buttons for the content sections could make some sense
- discoverability: do we use a cookie or localstorage to open the tutorial on first visit?

**Comment by stealthybox** [comment]
we could make tutorials from the existing material from Docker Global Mentor week
( how to use containers / how to `swarm init` )
windows stuff will have to be left out

for the new 1.13 stuff, a `deploy --compose-file` tutorial could be cool

links to useful official docker documentation could help UX.

**Comment by marcosnils** [comment]
> markdown for the content sections

YES, so we can leverage on all existing docker open source tutorials https://github.com/docker/labs

> we need some way to effectively show users when to switch to certain docker instances
> (since we're not working with a single console like Go)

One idea is to pre-create and display all the instances of that tutorial. I don't think that for tutorials more than two instances would be necessary

> where does the tutorial button go?

We can create a different subdomain like tour.play-with-docker.com with a different interface for this. I think we should definitely do it that way.

> we could anchor the instance buttons in the tutorial content by index

I'm not sure if I get this one.

> discoverability: do we use a cookie or localstorage to open the tutorial on first visit?

Yup, so if the user comes back, he can resume from where he left.


> for the new 1.13 stuff, a deploy --compose-file tutorial could be cool
> 
> links to useful official docker documentation could help UX.

:+1:

**Comment by marcosnils** [comment]
This will get closed when #79 lands.
