### ISSUE TITLE
Support for own base container

### ISSUE THREAD

**Issue by radu-matei** [play-with-docker/play-with-docker#187]
In the settings pane it would be awesome to provide my own image for the instances.
For example, if I'm testing, I don't want to always install prerequisites.

What do you think?

**Comment by marcosnils** [comment]
we thought about that, the problem is that we don't want people to arbitrarily specify their images and then fill up the server disk. We're adding Oauth log-in (Github / Google / etc) so we can enable features like this and punish malicious users. 
Do you think something else could be done in the mean time to give more flexibility?

**Comment by radu-matei** [comment]
That sounds very good!

I think that you can have some polls here / twitter and ask users what they would use.
Then maybe come up with 5/10 images that have the most popular demands.

Just a thought.

**Comment by 1138-4EB** [comment]
@marcosnils , just wondering whether this Oauth feature to support GitHub login is still in the roadmap.
