### ISSUE TITLE
Embed Dockerfile editor in PWD

### ISSUE THREAD

**Issue by rcjsuen** [play-with-docker/play-with-docker#242]
I have a Dockerfile editor [running in the browser](https://rcjsuen.github.io/dockerfile-language-service/) that may be of interest to PWD users. It is built on top of Microsoft's [Monaco Editor](https://microsoft.github.io/monaco-editor/).

Is there any interest in embedding it (or any other browser-based editor in general) into PWD somehow?

**Comment by marcosnils** [comment]
Hey Remy

PWD already has en embedded editor which is based on ace editor. If you go
to play-with-docker.com you should see an `editor` button for that purpose.

Is that what you mean?. Or is there any other ideas you have in mind?

sent from mobile


On Feb 17, 2018 00:03, "Remy Suen" <notifications@github.com> wrote:

I have a Dockerfile editor running in the browser
<https://rcjsuen.github.io/dockerfile-language-service/> that may be of
interest to PWD users. It is built on top of Microsoft's Monaco Editor
<https://microsoft.github.io/monaco-editor/>.

Is there any interest in embedding it (or any other browser-based editor in
general) into PWD somehow?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/play-with-docker/play-with-docker/issues/242>, or mute
the thread

**Comment by rcjsuen** [comment]
@marcosnils When I click on that button, I get a window for uploading files. When I click on it, I don't see any space for typing anything. Am I clicking on the wrong button?

![image](https://user-images.githubusercontent.com/15629116/36345626-1f42e070-1472-11e8-93a3-50dbcbc490b7.png)

**Comment by marcosnils** [comment]
Remy, you need to create a file in the terminal in order to see it there.
I.E if you do a `touch test` and then open the editor you'll see the file
there

sent from mobile

On Feb 17, 2018 18:09, "Remy Suen" <notifications@github.com> wrote:

@marcosnils <https://github.com/marcosnils> When I click on that button, I
get a window for uploading files. When I click on it, I don't see any space
for typing anything. Am I clicking on the wrong button?

[image: image]
<https://user-images.githubusercontent.com/15629116/36345626-1f42e070-1472-11e8-93a3-50dbcbc490b7.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/play-with-docker/play-with-docker/issues/242#issuecomment-366471542>,
or mute the thread

**Comment by rcjsuen** [comment]
Yes, I see it now, thanks!

I was thinking it would be nice to offer an editor that provided syntax highlighting and other features for editing a Dockerfile. However, I see now that what we have in PWD is a generic text editor. This is of course better than having an editor just for Dockerfiles. Perhaps it can be enhanced to provide syntax highlighting for any type of file.

**Comment by marcosnils** [comment]
@rcjsuen AFIAK ace editor supports highlighting based on different file types. We haven't included that in PWD yet but we'd love to do it. If you'd like to contribute and provide a Dockerfile [syntax highlighter](https://ace.c9.io/#nav=higlighter)  for ace we'll happily include it. I'll go ahead and close this for the moment
