### ISSUE TITLE
PWD session port and cpu usage is not getting accessed?

### ISSUE THREAD

**Issue by anandbhagwat** [play-with-docker/play-with-docker#322]

**Comment by ricardolimaui** [comment]
Hello all, this issue was closed, but I am having exactly the same problem. 

I am able to deploy the pwd properly, but when I initiate the session is not appearing the cpu and memory usage in the page. 
The same happens with the ports. I am able to deploy the docker properly, but the port does not appear. If I click in open port I insert the port I can see the docker is running ok.

I am running the pwd self hosted in ubuntu 16. I don't get any error error at PWD, so I don't know exactly what is wrong

Thank you
