### ISSUE TITLE
Ping between images not working

### ISSUE THREAD

**Issue by brunopenso** [play-with-docker/play-with-docker#359]
Hi  Guys,

Today I made a demo with drupal and postgres sql. 

I have to container with name mydb and mysite.

Inside the container mysite I can't ping "mydb" but I can ping the ip address of that container.

On my local machine the ping using the container name works well. 

Maybe Is there some issue with this?

**Comment by marcosnils** [comment]
@brunopenso this is because you're probably using the default network which doesn't resolve container names. You need to put both containers in the same (non-default) network for that to work.

More info here: https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
