### ISSUE TITLE
[Question] Can I use service for educational purposes? Are there any legal issues?

### ISSUE THREAD

**Issue by ADKosm** [play-with-docker/play-with-docker#427]
Hello, I am a lecturer in Higher School of Economics (https://www.hse.ru/en/).

I am creating online course for Coursera platform and I want to use service https://play-with-docker.com in this course in order to demonstrate docker capabilities and help students to practice with docker tools in browser.

I am not an expert in legal issues. I read information on the official site including "Terms of Use" of original docker (https://www.docker.com/legal/docker-terms-service) and as I can understand, I do not violate any copyright with my purpose of use. Of course I put all links and other attribution information but I am not sure for 100% that it is enough.

So, can you help me with this legal issues? Can I use service play-with-docker.com in my online course? Should I obtain license, or approve from you or somewhat else?

Thanks in advance

**Comment by marcosnils** [comment]
> So, can you help me with this legal issues? Can I use service play-with-docker.com in my online course? Should I obtain license, or approve from you or somewhat else?

You can use this service and redirect the users to this website like any other end user would use the service. Take into account that we don't provide any sort of SLA, so it might be possible that the platform is unavailable at some point for some users because there's a lot of users using it. 

Not so long ago someone from UC Davis in partnership with coursera started a project about developing a custom integration of PWD with their plugin system. We got a PoC working but eventually UC Davis lost interest and the project got kind of abandoned. 

If you know someone in Coursera that would like to  retake conversations we're happy to chat about possibilities.

**Comment by ADKosm** [comment]
It is amazing, thank you!

I am working with Coursera as a partner from my university, so unfortunately I don't know a lot of people in Coursera.
Actually, I was thinking about deep integration with Coursera also, but I came to conclusion, that there is no such benefits from huge development effort for plugin or somewhat else. Therefore, I am going to just show how to use service on the video and provide links and instructions for students to play with this service.
