### ISSUE TITLE
Question about instances IP addresses

### ISSUE THREAD

**Issue by exactsameproblem** [play-with-docker/play-with-docker#583]
Hello there,
On labs.play-with-docker.com I can see that the private IP set for the instances are always (?) the same : 192.168.0.8, 192.168.0.7...
On my local setup they are 10.0.X.Y and unlike on your demo site, mine are always incremented (when you close and open a new session)

The problem is that:
1. One can guess previously used/active IP addresses
2. I'm not sure what would happen once we reach all the ip range? 

Also I'm not sure why I get another ip range than yours?

I didn't find enough information in the source code/issue, so I'm asking here if it can help someone else as well?
Thank you very much.
Max

**Comment by marcosnils** [comment]
labs.play-with-docker.com uses some closed source parts to improve environment hardening and network optimizations. That's one of the reasons of why you see the same IP addresses being used each time. 

re:

> 2\. I'm not sure what would happen once we reach all the ip range?

I'm not sure if this will be practically possible since the default deployment strategy uses a /24 for each session which means that networking-wise you could have up to 255 sessions per PWD host. Having said that, you can always tune this settings at the `docker` engine level (https://docs.docker.com/engine/reference/commandline/network_create/#options). Check the `subnet` option there.

**Comment by exactsameproblem** [comment]
Thank you Marcos for your quick answer!
Can you share a little bit more info about environment hardening for PWD? because I understand from your message that we are deploying less secure installation by default? Would it be a security consideration for a production version?

**Comment by marcosnils** [comment]
> because I understand from your message that we are deploying less secure installation by default? Would it be a security consideration for a production version?

By default PWD is set to start in `privileged` mode (https://github.com/play-with-docker/play-with-docker/blob/master/api.go#L55) to allow some processes like `dockerd` to be able to work. Privileged containers expose some security vulnerabilities (users can easily escalate to the underlying host) if you open your playground to the outside world and let anyone run anything in them.

**Comment by exactsameproblem** [comment]
Are you saying that PWD as-is isn't secured and not ready for production environment?
If yes, would it be possible to elaborate on the hardening you talk about and/or add a security note? Can I just turn off Privileged containers?
Thanks
