### ISSUE TITLE
I'm trying to launch labs.play-with-k8s locally

### ISSUE THREAD

**Issue by fams** [play-with-docker/play-with-docker#626]
Hello Folks,
I'm trying to lauch a labs.play-with-k8s.com locally. 
In some old issues, I've seen a configuration to set DIND_IMAGE=franela/k8s . The tip does not say where  or if it will work with docker-compose. Is it possible to setup labs.play-with-k8slocally nowdays?
Thanks

**Comment by marcosnils** [comment]
yes it is possible. Are you trying to run the `docker` or `k8s` variant?

**Comment by fams** [comment]
K8S variant

**Comment by chichi13** [comment]
I figured out how to run play with k8s locally:
- Change `franela/docker` to `franela/k8s` in `api.go`.
- Change `AssetsDir` in `handlers/bootstrap.go` to `k8s` instead of `default`.

Then make the changes for the domain name in `config/config.go`

`docker compose up -d` and it should work, but I don't know if it's the proper way to run PWK. @marcosnils could you please confirm, so I can add it to the README.md

**Comment by fams** [comment]
I dit it, but there is underline OS issues.
1. Using ubutuntu 18.04 -> 20.04 i'm receiving an error to unapck containers if crictl is used to pull images. Docker pull is working, i don't know what is happening. The issue seems to be related to filesystem options, but no clue how to solve it
2. need to uninstall apparmor in Linux to make the creation works. 
4. Using ubuntu 24.04 succeffully created an instance of franela/k8s, But kubeadminit does not complete, pods isn't starting , something related to cgroupsv2 i think

**Comment by chichi13** [comment]
"The issue seems to be related to filesystem options, but no clue how to solve it" --> I've seen that on Ubuntu 22.04 the storage driver used by `franela/k8s` was different between my setup and the labs play with k8s setup. Mine was using an old one.

So, finally did you manage to run it successfully on Ubuntu 22.04 after uninstalling apparmor?

**Comment by fams** [comment]
Not yet, did you get it? What is your complete setup?
Docker Version
Distro
Filesystems,
Etc

**Comment by fams** [comment]
Still not working with 22.0.4.  same problemas from 18.0.4, 20.04 and 22.0.4
the same extract error
E1014 23:26:39.162897     428 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.27.16\": failed to extract layer sha256:06d84c7e474c1b4311890a004c0880577d0fb8d3b89639b7541765289ca36355: failed to convert whiteout file \"usr/local/.wh..wh..opq\": operation not supported: unknown" image="registry.k8s.io/kube-scheduler:v1.27.16"
FATA[0006] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/kube-scheduler:v1.27.16": failed to extract layer sha256:06d84c7e474c1b4311890a004c0880577d0fb8d3b89639b7541765289ca36355: failed to convert whiteout file "usr/local/.wh..wh..opq": operation not supported: unknown

**Comment by chichi13** [comment]
I no longer have access to the machine because it's been cancelled, but it was an Ubuntu 22.04 with the latest version of docker as of October 03 (i.e. 27.3.1). The file system used by docker was overlay2 on my host. Play with docker worked fine, but not play with kubernetes.

**Comment by fams** [comment]
I've managed to make PWD works in all Ubuntu versions, but PWK didn't works in any
