### ISSUE TITLE
Add the option for restarting the timer when it runs out with persistence for active instances.

### ISSUE THREAD

**Issue by ishantanu** [play-with-docker/play-with-docker#80]
Is there any possibility of giving the option for saving the state of instance when the timer runs out. And give an extra option to the user to restart the timer along with the previously active instances and work.

Or maybe give an option for extending the timer and session when 10 or so minutes are left before timer runs down.

Consider the below scenario:
1. A user have **n** number of active instances for **m** hours.
2. Now, when **m = 3**, the session will be closed regardless of the number of active instances.
3. But what if the user wanted to continue his work beyond **3 hours**?
4. Is there any possibility of doing the provision for restarting the time left but persisting the active work.

Just a thought.

**Comment by marcosnils** [comment]
@iamShantanu101 the idea behind PWD is for it to be a playground where you can try stuff or use it to give a presentation about docker or any of it's features. The original idea of the session timeout is mainly because we don't want bots or malicious users to take ownership of the machine and start doing things like mining bitcoins (it happened in the past)

I also understand that after the session expires in 4 hours (which seems like a reasonable time) you can just create a new one and it'd be nice to resume the work you were doing. But at the same time, if you need to work more 4 hours in PWD, it feels like you're not using it for what it was intended to.  

I'm not sure about this, as stated before, the idea is for it to be "stateless". Maybe, if this specific use case becomes requested a lot, we could evaluate to do persisted sessions and maybe charge something for that, but for the moment I'd prefer to leave it as it and stick with the original idea

**Comment by iamShantanu101** [comment]
@marcosnils Surely, this is intended to be a playground and with due respect looks good. Monetizing the feature of persistence might or might not play well with the users. This was just a thought anyways. Lets see how this goes further.

**Comment by xetorthio** [comment]
Do you have a specific use case in mind? What are you doing with pwd that
takes more than 4 hours?

**Comment by iamShantanu101** [comment]
@xetorthio As I mentioned, this was just a thought. Of course "stateless" is how pwd works. Look at the evolution of Docker. It was all "stateless". It still is the better way to go. And as the evolution continues, docker is catering the need for "stateful" applications too. Obviously peoples have a use case to deploy stateful applications with Docker. Its just that I am quite unsure about how and when peoples might come with the same kind of approach here. I was just discussing a possibility.

**Comment by xetorthio** [comment]
Yeah. As @marcosnils said, let's wait until a valid use case shows up with
need of a stateful or long lived playground

**Comment by bbarman4u** [comment]
@marcosnils Thanks for this excellent initiative with the PWD. I would also like to know if there can be an option to set the session configurable up to a max of certain time. It probably does not have to be exposed on the hosted browser version (and I agree with all the concerns in this thread) but will be very useful for self hosted instances on local machines where one has a demo environment set up and may we want to demonstrate certain other capabilities in association with docker which might take time for the students or users in a workshop to set it up and only to expire in 4 hours and again they have to set it up twice.

**Comment by marcosnils** [comment]
> Thanks for this excellent initiative with the PWD

It's a join effort with @xetorthio and some other contributors :muscle: . 

> I would also like to know if there can be an option to set the session timeout configurable up to a max of certain time

That is already supported and configurable. Check https://github.com/play-with-docker/play-with-docker/blob/c0aaf0a3a4a1cf172b06f4873f28bb5b19ca1152/api.go#L51-L55
